version: '3.8'

services:
  backend:
    build: ./backend
    container_name: bloc-notas-backend
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    command: npm start
