version: '3.8'

services:
  backend:
    build: ./backend
    container_name: bloc-notas-backend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules  # <-- Esto evita que se sobrescriban los node_modules
    command: npm start
